image: python:3.5


stages:
 - check
 - build1
 - build2
 - test
 - deploy


check_pep8:
 stage: check
 script: make pip_check_pep8

check_lint:
 stage: check
 script: make pip_check_lint

check_complexity:
 stage: check
 script: make pip_check_complexity

build_doc:
 stage: build1
 script: make pip_build_doc
 artifacts:
  name: Documentation
  paths:
   - docs/_build/

build_package:
 stage: build1
 script: make pip_build_package
 artifacts:
  name: Python package
  paths:
   - dist/

build_container:
 stage: build2
 script: make pip_build_container
 dependencies:
  - build_package
  - build_doc

deploy_package_staging:
 stage: deploy
 script: make pip_deploy_package_staging
 dependencies:
  - build_package
 only:
  - master
