image: python:3.5


stages:
 - check
 - build1
 - build2
 - test
 - deploy


check_pep8:
 stage: check
 script: make pip_check_pep8

check_lint:
 stage: check
 script: make pip_check_lint

check_complexity:
 stage: check
 script: make pip_check_complexity

build_doc:
 stage: build1
 script: make pip_build_doc
 artifacts:
  name: Documentation
  paths:
   - docs/_build/

build_package:
 stage: build1
 script: make pip_build_package
 artifacts:
  name: Python package
  paths:
   - dist/

build_plugin:
 stage: build2
 image: docker:stable
 services:
   - docker:dind
 variables:
   DOCKER_HOST: tcp://docker:2375
   DOCKER_DRIVER: overlay2
 tags:
  - docker
 # script: make build_plugin
 script: images/docker-plugin/create_plugin.sh
 dependencies:
  - build_package
 artifacts:
  name: Docker plugin
  paths:
   - _build/docker-plugin

deploy_package_staging:
 stage: deploy
 script: make pip_deploy_package_staging
 dependencies:
  - build_package
 only:
  - master
