stages:
 - check
 - build1
 - build2
 - test
 - deploy


check_pep8:
 stage: check
 script: make check_pep8

check_lint:
 stage: check
 script: make check_lint

check_complexity:
 stage: check
 script: make check_complexity

build_doc:
 stage: build1
 script: make build_doc
 artifacts:
  name: Documentation
  paths:
   - docs/_build/

build_package:
 stage: build1
 script: make build_package
 artifacts:
  name: Python package
  paths:
   - dist/

build_container:
 stage: build2
 script: make build_container
 dependencies:
  - build_package
  - build_doc

deploy_package_staging:
 stage: deploy
 script: make deploy_package_staging
 dependencies:
   - build_package
